server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: configuration
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

# Post-Implementation Support: Enhanced monitoring and observability
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,configprops,env,beans,configserver
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
    configserver:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
  health:
    diskspace:
      enabled: true
    ping:
      enabled: true

logging:
  level:
    org.springframework.cloud.config: INFO
    org.springframework.boot.actuator: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/configuration.log
    max-size: 10MB
    max-history: 30
