eureka:
  client:
    register-with-eureka: false
server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: test
          uri: http://httpbin.org/
          predicates:
            - Path=/uuid
        - id: users
          uri: http://localhost:8090/
          predicates:
            - Path=/api/v1/users/**
        - id: access
          uri: http://localhost:8090/
          predicates:
            - Path=/api/v1/access/**

# Post-Implementation Support: Enhanced monitoring and observability
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,configprops,env,gateway,beans
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        gateway.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
        gateway.requests: 0.5, 0.9, 0.95, 0.99
  health:
    diskspace:
      enabled: true
    ping:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web.reactive: INFO
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/gateway.log
    max-size: 10MB
    max-history: 30
