eureka:
  client:
    register-with-eureka: false
server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: test
          uri: http://httpbin.org/
          predicates:
            - Path=/uuid
        - id: users
          uri: http://localhost:8090/
          predicates:
            - Path=/api/v1/users/**
        - id: access
          uri: http://localhost:8090/
          predicates:
            - Path=/api/v1/access/**
        - id: channel-management
          uri: lb://channel-management
          predicates:
            - Path=/api/channels/**
        - id: integration-service
          uri: lb://integration-service
          predicates:
            - Path=/api/integrations/**

management:
  tracing:
    sampling:
      probability: 1.0
